services:
  bitacora:
    image: ghcr.io/ignaciominguezm/bitacora:latest
    container_name: bitacora
    restart: unless-stopped
    ports:
      - "3006:3006"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ignacio-net

  migrator:
    image: ghcr.io/ignaciominguezm/bitacora:latest
    command: ["node", "dist/migrate.js"]
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ignacio-net
    restart: "no"

networks:
  ignacio-net:
    external: true
